### ISSUE TITLE
tcia-lidc-xml has 6 folders containing xml files, which choose  ?

### ISSUE THREAD

**Issue by MiGoetz** [MIC-DKFZ/LIDC-IDRI-processing#2]
tcia-lidc-xml has 6 folders containing xml files, which choose  ?

_Originally posted by @wgs123 in https://github.com/MIC-DKFZ/LIDC-IDRI-processing/issues/1#issuecomment-478639771_

**Comment by MiGoetz** [comment]
You should choose the folder, containing the other folders with the XML files in it.

**Comment by mirnegarian** [comment]
Hi Michael,

Thank you for this great code. I have also this question that is there any difference between *.xml files within the tcia-lidc-xml and the ones inside each CT folder?

**Comment by MiGoetz** [comment]
I didn't figured out what's in the XML inside each CT folder and didn't used them.  I got all my information from the official documents and by reverse-engineering/try and error, as I'm not an officially linked to the project.

**Comment by MiGoetz** [comment]
I'm closing this issue, feel free to reopen it / a new one if the question is not sufficiently answered.
